### ISSUE TITLE
Bruh,

### ISSUE THREAD

**Issue by whippingdot** [whippingdot/FriendsCoding#1]
Bro, we have to create some files. Hope you can join for some coding today(21 oct) but if you can't then just update the chips.py file. Start the file off. The goal for us is to create a game of chips, where there will be some number of chips below 100, and the player who takes the last chip loses. We can add some extra things like where if you reach a number, something good or bad happens to you.

**Comment by whippingdot** [comment]
You try to start the project Neil. Loki, if you  have time please do it.

**Comment by whippingdot** [comment]
I have started it. I created a second branch called chips1, please edit the chips.py file in that.

**Comment by NRafa1391** [comment]
Dear Sanjay,
????

**Comment by whippingdot** [comment]
What Neil? Read the earlier comments.

> Bro, we have to create some files. Hope you can join for some coding today(21 oct) but if you can't then just update the chips.py file. Start the file off. The goal for us is to create a game of chips, where there will be some number of chips below 100, and the player who takes the last chip loses. We can add some extra things like where if you reach a number, something good or bad happens to you.

**Comment by whippingdot** [comment]
I am closing this issue and creating a new issue so u understand
