### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by NRafa1391** [whippingdot/FriendsCoding#4]
bruh, can't see output. On what should I open on?
I opened on an IP address from 200 OK! server

**Comment by NRafa1391** [comment]
BTW it is Chips.py that is just showing some text
The others are 
![download (1)](https://user-images.githubusercontent.com/71452634/99882183-97bbd600-2c44-11eb-87d3-1b33c3921439.jpg)

**Comment by whippingdot** [comment]
I haven't edited chips.py. I told you to do it. Run it on whatever you want. I use VS Code.

**Comment by NRafa1391** [comment]
I have no idea how to use Python -_-  Sent from Mail for Windows 10 From: Sanjaay R.Sent: Sunday, November 22, 2020 10:45 AMTo: whippingdot/FriendsCodingCc: Ying-Yang Spinny Thang; AuthorSubject: Re: [whippingdot/FriendsCoding] halp (#4) I haven't edited chips.py. I told you to do it. Run it on whatever you want. I use VS Code.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by whippingdot** [comment]
What????

**Comment by NRafa1391** [comment]
Ok, I did **not** see that coming

**Comment by NRafa1391** [comment]
I replied from Mail, so it must have been messed up in some or the other way. Eek.
