### ISSUE TITLE
Physics-based game using engine

### ISSUE THREAD

**Issue by NRafa1391** [whippingdot/FriendsCoding#5]
Hey, Sanjaay, do you wish to partake in the act of creating a game that does run on a physics engine?
If you do wish to, please beckon my attention.

**Comment by NRafa1391** [comment]
For python, [this](https://github.com/openai/mujoco-py.git) has most stars.
I use [this physics engine](https://github.com/liabru/matter-js.git) for my stuff in JavaScript.
C++ means [this](https://github.com/erincatto/box2d.git)

**Comment by whippingdot** [comment]
I have no idea how to use physics engines.
